package model;
// Generated 19/06/2017 17:16:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CertificatesGeneratedcertificate generated by hbm2java
 */
public class CertificatesGeneratedcertificate  implements java.io.Serializable {


     private int id;
     private int userId;
     private String downloadUrl;
     private String grade;
     private String courseId;
     private String key;
     private boolean distinction;
     private String status;
     private String verifyUuid;
     private String downloadUuid;
     private String name;
     private Date createdDate;
     private Date modifiedDate;
     private String errorReason;
     private String mode;

    public CertificatesGeneratedcertificate() {
    }

    public CertificatesGeneratedcertificate(int id, int userId, String downloadUrl, String grade, String courseId, String key, boolean distinction, String status, String verifyUuid, String downloadUuid, String name, Date createdDate, Date modifiedDate, String errorReason, String mode) {
       this.id = id;
       this.userId = userId;
       this.downloadUrl = downloadUrl;
       this.grade = grade;
       this.courseId = courseId;
       this.key = key;
       this.distinction = distinction;
       this.status = status;
       this.verifyUuid = verifyUuid;
       this.downloadUuid = downloadUuid;
       this.name = name;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.errorReason = errorReason;
       this.mode = mode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getDownloadUrl() {
        return this.downloadUrl;
    }
    
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public boolean isDistinction() {
        return this.distinction;
    }
    
    public void setDistinction(boolean distinction) {
        this.distinction = distinction;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getVerifyUuid() {
        return this.verifyUuid;
    }
    
    public void setVerifyUuid(String verifyUuid) {
        this.verifyUuid = verifyUuid;
    }
    public String getDownloadUuid() {
        return this.downloadUuid;
    }
    
    public void setDownloadUuid(String downloadUuid) {
        this.downloadUuid = downloadUuid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getErrorReason() {
        return this.errorReason;
    }
    
    public void setErrorReason(String errorReason) {
        this.errorReason = errorReason;
    }
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }




}


