package model;
// Generated 19/06/2017 17:16:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EdxTrackEvent generated by hbm2java
 */
public class EdxTrackEvent  implements java.io.Serializable {


     private String id;
     private String eventId;
     private String agent;
     private String eventSource;
     private String eventType;
     private String ipCountry;
     private String page;
     private String session;
     private Date time;
     private String anonScreenName;
     private Date downtimeFor;
     private String studentId;
     private String instructorId;
     private String courseId;
     private String courseDisplayName;
     private String resourceDisplayName;
     private String organization;
     private String sequenceId;
     private int gotoFrom;
     private int gotoDest;
     private String problemId;
     private String problemChoice;
     private String questionLocation;
     private String submissionId;
     private int attempts;
     private String longAnswer;
     private String studentFile;
     private String canUploadFile;
     private String feedback;
     private byte feedbackResponseSelected;
     private String transcriptId;
     private String transcriptCode;
     private int rubricSelection;
     private int rubricCategory;
     private String videoId;
     private String videoCode;
     private String videoCurrentTime;
     private String videoSpeed;
     private String videoOldTime;
     private String videoNewTime;
     private String videoSeekType;
     private String videoNewSpeed;
     private String videoOldSpeed;
     private String bookInteractionType;
     private String success;
     private String answerId;
     private String hint;
     private String mode;
     private String msg;
     private byte npoints;
     private String queuestate;
     private int origScore;
     private int newScore;
     private int origTotal;
     private int newTotal;
     private String eventName;
     private String groupUser;
     private String groupAction;
     private int position;
     private String badlyFormatted;
     private String correctMapFk;
     private String answerFk;
     private String stateFk;
     private String loadInfoFk;

    public EdxTrackEvent() {
    }

    public EdxTrackEvent(String id, String eventId, String agent, String eventSource, String eventType, String ipCountry, String page, String session, Date time, String anonScreenName, Date downtimeFor, String studentId, String instructorId, String courseId, String courseDisplayName, String resourceDisplayName, String organization, String sequenceId, int gotoFrom, int gotoDest, String problemId, String problemChoice, String questionLocation, String submissionId, int attempts, String longAnswer, String studentFile, String canUploadFile, String feedback, byte feedbackResponseSelected, String transcriptId, String transcriptCode, int rubricSelection, int rubricCategory, String videoId, String videoCode, String videoCurrentTime, String videoSpeed, String videoOldTime, String videoNewTime, String videoSeekType, String videoNewSpeed, String videoOldSpeed, String bookInteractionType, String success, String answerId, String hint, String mode, String msg, byte npoints, String queuestate, int origScore, int newScore, int origTotal, int newTotal, String eventName, String groupUser, String groupAction, int position, String badlyFormatted, String correctMapFk, String answerFk, String stateFk, String loadInfoFk) {
       this.id = id;
       this.eventId = eventId;
       this.agent = agent;
       this.eventSource = eventSource;
       this.eventType = eventType;
       this.ipCountry = ipCountry;
       this.page = page;
       this.session = session;
       this.time = time;
       this.anonScreenName = anonScreenName;
       this.downtimeFor = downtimeFor;
       this.studentId = studentId;
       this.instructorId = instructorId;
       this.courseId = courseId;
       this.courseDisplayName = courseDisplayName;
       this.resourceDisplayName = resourceDisplayName;
       this.organization = organization;
       this.sequenceId = sequenceId;
       this.gotoFrom = gotoFrom;
       this.gotoDest = gotoDest;
       this.problemId = problemId;
       this.problemChoice = problemChoice;
       this.questionLocation = questionLocation;
       this.submissionId = submissionId;
       this.attempts = attempts;
       this.longAnswer = longAnswer;
       this.studentFile = studentFile;
       this.canUploadFile = canUploadFile;
       this.feedback = feedback;
       this.feedbackResponseSelected = feedbackResponseSelected;
       this.transcriptId = transcriptId;
       this.transcriptCode = transcriptCode;
       this.rubricSelection = rubricSelection;
       this.rubricCategory = rubricCategory;
       this.videoId = videoId;
       this.videoCode = videoCode;
       this.videoCurrentTime = videoCurrentTime;
       this.videoSpeed = videoSpeed;
       this.videoOldTime = videoOldTime;
       this.videoNewTime = videoNewTime;
       this.videoSeekType = videoSeekType;
       this.videoNewSpeed = videoNewSpeed;
       this.videoOldSpeed = videoOldSpeed;
       this.bookInteractionType = bookInteractionType;
       this.success = success;
       this.answerId = answerId;
       this.hint = hint;
       this.mode = mode;
       this.msg = msg;
       this.npoints = npoints;
       this.queuestate = queuestate;
       this.origScore = origScore;
       this.newScore = newScore;
       this.origTotal = origTotal;
       this.newTotal = newTotal;
       this.eventName = eventName;
       this.groupUser = groupUser;
       this.groupAction = groupAction;
       this.position = position;
       this.badlyFormatted = badlyFormatted;
       this.correctMapFk = correctMapFk;
       this.answerFk = answerFk;
       this.stateFk = stateFk;
       this.loadInfoFk = loadInfoFk;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }
    public String getAgent() {
        return this.agent;
    }
    
    public void setAgent(String agent) {
        this.agent = agent;
    }
    public String getEventSource() {
        return this.eventSource;
    }
    
    public void setEventSource(String eventSource) {
        this.eventSource = eventSource;
    }
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    public String getIpCountry() {
        return this.ipCountry;
    }
    
    public void setIpCountry(String ipCountry) {
        this.ipCountry = ipCountry;
    }
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }
    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getAnonScreenName() {
        return this.anonScreenName;
    }
    
    public void setAnonScreenName(String anonScreenName) {
        this.anonScreenName = anonScreenName;
    }
    public Date getDowntimeFor() {
        return this.downtimeFor;
    }
    
    public void setDowntimeFor(Date downtimeFor) {
        this.downtimeFor = downtimeFor;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(String instructorId) {
        this.instructorId = instructorId;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getCourseDisplayName() {
        return this.courseDisplayName;
    }
    
    public void setCourseDisplayName(String courseDisplayName) {
        this.courseDisplayName = courseDisplayName;
    }
    public String getResourceDisplayName() {
        return this.resourceDisplayName;
    }
    
    public void setResourceDisplayName(String resourceDisplayName) {
        this.resourceDisplayName = resourceDisplayName;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId;
    }
    public int getGotoFrom() {
        return this.gotoFrom;
    }
    
    public void setGotoFrom(int gotoFrom) {
        this.gotoFrom = gotoFrom;
    }
    public int getGotoDest() {
        return this.gotoDest;
    }
    
    public void setGotoDest(int gotoDest) {
        this.gotoDest = gotoDest;
    }
    public String getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(String problemId) {
        this.problemId = problemId;
    }
    public String getProblemChoice() {
        return this.problemChoice;
    }
    
    public void setProblemChoice(String problemChoice) {
        this.problemChoice = problemChoice;
    }
    public String getQuestionLocation() {
        return this.questionLocation;
    }
    
    public void setQuestionLocation(String questionLocation) {
        this.questionLocation = questionLocation;
    }
    public String getSubmissionId() {
        return this.submissionId;
    }
    
    public void setSubmissionId(String submissionId) {
        this.submissionId = submissionId;
    }
    public int getAttempts() {
        return this.attempts;
    }
    
    public void setAttempts(int attempts) {
        this.attempts = attempts;
    }
    public String getLongAnswer() {
        return this.longAnswer;
    }
    
    public void setLongAnswer(String longAnswer) {
        this.longAnswer = longAnswer;
    }
    public String getStudentFile() {
        return this.studentFile;
    }
    
    public void setStudentFile(String studentFile) {
        this.studentFile = studentFile;
    }
    public String getCanUploadFile() {
        return this.canUploadFile;
    }
    
    public void setCanUploadFile(String canUploadFile) {
        this.canUploadFile = canUploadFile;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public byte getFeedbackResponseSelected() {
        return this.feedbackResponseSelected;
    }
    
    public void setFeedbackResponseSelected(byte feedbackResponseSelected) {
        this.feedbackResponseSelected = feedbackResponseSelected;
    }
    public String getTranscriptId() {
        return this.transcriptId;
    }
    
    public void setTranscriptId(String transcriptId) {
        this.transcriptId = transcriptId;
    }
    public String getTranscriptCode() {
        return this.transcriptCode;
    }
    
    public void setTranscriptCode(String transcriptCode) {
        this.transcriptCode = transcriptCode;
    }
    public int getRubricSelection() {
        return this.rubricSelection;
    }
    
    public void setRubricSelection(int rubricSelection) {
        this.rubricSelection = rubricSelection;
    }
    public int getRubricCategory() {
        return this.rubricCategory;
    }
    
    public void setRubricCategory(int rubricCategory) {
        this.rubricCategory = rubricCategory;
    }
    public String getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(String videoId) {
        this.videoId = videoId;
    }
    public String getVideoCode() {
        return this.videoCode;
    }
    
    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode;
    }
    public String getVideoCurrentTime() {
        return this.videoCurrentTime;
    }
    
    public void setVideoCurrentTime(String videoCurrentTime) {
        this.videoCurrentTime = videoCurrentTime;
    }
    public String getVideoSpeed() {
        return this.videoSpeed;
    }
    
    public void setVideoSpeed(String videoSpeed) {
        this.videoSpeed = videoSpeed;
    }
    public String getVideoOldTime() {
        return this.videoOldTime;
    }
    
    public void setVideoOldTime(String videoOldTime) {
        this.videoOldTime = videoOldTime;
    }
    public String getVideoNewTime() {
        return this.videoNewTime;
    }
    
    public void setVideoNewTime(String videoNewTime) {
        this.videoNewTime = videoNewTime;
    }
    public String getVideoSeekType() {
        return this.videoSeekType;
    }
    
    public void setVideoSeekType(String videoSeekType) {
        this.videoSeekType = videoSeekType;
    }
    public String getVideoNewSpeed() {
        return this.videoNewSpeed;
    }
    
    public void setVideoNewSpeed(String videoNewSpeed) {
        this.videoNewSpeed = videoNewSpeed;
    }
    public String getVideoOldSpeed() {
        return this.videoOldSpeed;
    }
    
    public void setVideoOldSpeed(String videoOldSpeed) {
        this.videoOldSpeed = videoOldSpeed;
    }
    public String getBookInteractionType() {
        return this.bookInteractionType;
    }
    
    public void setBookInteractionType(String bookInteractionType) {
        this.bookInteractionType = bookInteractionType;
    }
    public String getSuccess() {
        return this.success;
    }
    
    public void setSuccess(String success) {
        this.success = success;
    }
    public String getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(String answerId) {
        this.answerId = answerId;
    }
    public String getHint() {
        return this.hint;
    }
    
    public void setHint(String hint) {
        this.hint = hint;
    }
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public byte getNpoints() {
        return this.npoints;
    }
    
    public void setNpoints(byte npoints) {
        this.npoints = npoints;
    }
    public String getQueuestate() {
        return this.queuestate;
    }
    
    public void setQueuestate(String queuestate) {
        this.queuestate = queuestate;
    }
    public int getOrigScore() {
        return this.origScore;
    }
    
    public void setOrigScore(int origScore) {
        this.origScore = origScore;
    }
    public int getNewScore() {
        return this.newScore;
    }
    
    public void setNewScore(int newScore) {
        this.newScore = newScore;
    }
    public int getOrigTotal() {
        return this.origTotal;
    }
    
    public void setOrigTotal(int origTotal) {
        this.origTotal = origTotal;
    }
    public int getNewTotal() {
        return this.newTotal;
    }
    
    public void setNewTotal(int newTotal) {
        this.newTotal = newTotal;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getGroupUser() {
        return this.groupUser;
    }
    
    public void setGroupUser(String groupUser) {
        this.groupUser = groupUser;
    }
    public String getGroupAction() {
        return this.groupAction;
    }
    
    public void setGroupAction(String groupAction) {
        this.groupAction = groupAction;
    }
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
    public String getBadlyFormatted() {
        return this.badlyFormatted;
    }
    
    public void setBadlyFormatted(String badlyFormatted) {
        this.badlyFormatted = badlyFormatted;
    }
    public String getCorrectMapFk() {
        return this.correctMapFk;
    }
    
    public void setCorrectMapFk(String correctMapFk) {
        this.correctMapFk = correctMapFk;
    }
    public String getAnswerFk() {
        return this.answerFk;
    }
    
    public void setAnswerFk(String answerFk) {
        this.answerFk = answerFk;
    }
    public String getStateFk() {
        return this.stateFk;
    }
    
    public void setStateFk(String stateFk) {
        this.stateFk = stateFk;
    }
    public String getLoadInfoFk() {
        return this.loadInfoFk;
    }
    
    public void setLoadInfoFk(String loadInfoFk) {
        this.loadInfoFk = loadInfoFk;
    }




}


